// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm.proto

package com.testnetdeve.custom.proto;

public final class AlarmProto {
  private AlarmProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AlarmOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Alarm)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string community = 2;</code>
     */
    boolean hasCommunity();
    /**
     * <code>optional string community = 2;</code>
     */
    String getCommunity();
    /**
     * <code>optional string community = 2;</code>
     */
    com.google.protobuf.ByteString
        getCommunityBytes();

    /**
     * <code>required int32 building_id = 3;</code>
     */
    boolean hasBuildingId();
    /**
     * <code>required int32 building_id = 3;</code>
     */
    int getBuildingId();

    /**
     * <code>optional string building_part = 4;</code>
     */
    boolean hasBuildingPart();
    /**
     * <code>optional string building_part = 4;</code>
     */
    String getBuildingPart();
    /**
     * <code>optional string building_part = 4;</code>
     */
    com.google.protobuf.ByteString
        getBuildingPartBytes();

    /**
     * <code>required int32 cell_id = 5;</code>
     */
    boolean hasCellId();
    /**
     * <code>required int32 cell_id = 5;</code>
     */
    int getCellId();

    /**
     * <code>required int32 room_id = 6;</code>
     */
    boolean hasRoomId();
    /**
     * <code>required int32 room_id = 6;</code>
     */
    int getRoomId();

    /**
     * <code>required string alarm_category = 7;</code>
     */
    boolean hasAlarmCategory();
    /**
     * <code>required string alarm_category = 7;</code>
     */
    String getAlarmCategory();
    /**
     * <code>required string alarm_category = 7;</code>
     */
    com.google.protobuf.ByteString
        getAlarmCategoryBytes();

    /**
     * <code>optional string attachment = 8;</code>
     */
    boolean hasAttachment();
    /**
     * <code>optional string attachment = 8;</code>
     */
    String getAttachment();
    /**
     * <code>optional string attachment = 8;</code>
     */
    com.google.protobuf.ByteString
        getAttachmentBytes();
  }
  /**
   * Protobuf type {@code Alarm}
   */
  public  static final class Alarm extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Alarm)
      AlarmOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Alarm.newBuilder() to construct.
    private Alarm(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Alarm() {
      community_ = "";
      buildingPart_ = "";
      alarmCategory_ = "";
      attachment_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Alarm(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              community_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              buildingId_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              buildingPart_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              cellId_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              roomId_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              alarmCategory_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              attachment_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AlarmProto.internal_static_Alarm_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AlarmProto.internal_static_Alarm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Alarm.class, Builder.class);
    }

    private int bitField0_;
    public static final int COMMUNITY_FIELD_NUMBER = 2;
    private volatile Object community_;
    /**
     * <code>optional string community = 2;</code>
     */
    public boolean hasCommunity() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string community = 2;</code>
     */
    public String getCommunity() {
      Object ref = community_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          community_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string community = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCommunityBytes() {
      Object ref = community_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        community_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUILDING_ID_FIELD_NUMBER = 3;
    private int buildingId_;
    /**
     * <code>required int32 building_id = 3;</code>
     */
    public boolean hasBuildingId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 building_id = 3;</code>
     */
    public int getBuildingId() {
      return buildingId_;
    }

    public static final int BUILDING_PART_FIELD_NUMBER = 4;
    private volatile Object buildingPart_;
    /**
     * <code>optional string building_part = 4;</code>
     */
    public boolean hasBuildingPart() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string building_part = 4;</code>
     */
    public String getBuildingPart() {
      Object ref = buildingPart_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          buildingPart_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string building_part = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBuildingPartBytes() {
      Object ref = buildingPart_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        buildingPart_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CELL_ID_FIELD_NUMBER = 5;
    private int cellId_;
    /**
     * <code>required int32 cell_id = 5;</code>
     */
    public boolean hasCellId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 cell_id = 5;</code>
     */
    public int getCellId() {
      return cellId_;
    }

    public static final int ROOM_ID_FIELD_NUMBER = 6;
    private int roomId_;
    /**
     * <code>required int32 room_id = 6;</code>
     */
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int32 room_id = 6;</code>
     */
    public int getRoomId() {
      return roomId_;
    }

    public static final int ALARM_CATEGORY_FIELD_NUMBER = 7;
    private volatile Object alarmCategory_;
    /**
     * <code>required string alarm_category = 7;</code>
     */
    public boolean hasAlarmCategory() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required string alarm_category = 7;</code>
     */
    public String getAlarmCategory() {
      Object ref = alarmCategory_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          alarmCategory_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string alarm_category = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAlarmCategoryBytes() {
      Object ref = alarmCategory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        alarmCategory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTACHMENT_FIELD_NUMBER = 8;
    private volatile Object attachment_;
    /**
     * <code>optional string attachment = 8;</code>
     */
    public boolean hasAttachment() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string attachment = 8;</code>
     */
    public String getAttachment() {
      Object ref = attachment_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          attachment_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string attachment = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAttachmentBytes() {
      Object ref = attachment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        attachment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBuildingId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCellId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoomId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAlarmCategory()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, community_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(3, buildingId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, buildingPart_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(5, cellId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(6, roomId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, alarmCategory_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, attachment_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, community_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, buildingId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, buildingPart_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, cellId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, roomId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, alarmCategory_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, attachment_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Alarm)) {
        return super.equals(obj);
      }
      Alarm other = (Alarm) obj;

      if (hasCommunity() != other.hasCommunity()) return false;
      if (hasCommunity()) {
        if (!getCommunity()
            .equals(other.getCommunity())) return false;
      }
      if (hasBuildingId() != other.hasBuildingId()) return false;
      if (hasBuildingId()) {
        if (getBuildingId()
            != other.getBuildingId()) return false;
      }
      if (hasBuildingPart() != other.hasBuildingPart()) return false;
      if (hasBuildingPart()) {
        if (!getBuildingPart()
            .equals(other.getBuildingPart())) return false;
      }
      if (hasCellId() != other.hasCellId()) return false;
      if (hasCellId()) {
        if (getCellId()
            != other.getCellId()) return false;
      }
      if (hasRoomId() != other.hasRoomId()) return false;
      if (hasRoomId()) {
        if (getRoomId()
            != other.getRoomId()) return false;
      }
      if (hasAlarmCategory() != other.hasAlarmCategory()) return false;
      if (hasAlarmCategory()) {
        if (!getAlarmCategory()
            .equals(other.getAlarmCategory())) return false;
      }
      if (hasAttachment() != other.hasAttachment()) return false;
      if (hasAttachment()) {
        if (!getAttachment()
            .equals(other.getAttachment())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCommunity()) {
        hash = (37 * hash) + COMMUNITY_FIELD_NUMBER;
        hash = (53 * hash) + getCommunity().hashCode();
      }
      if (hasBuildingId()) {
        hash = (37 * hash) + BUILDING_ID_FIELD_NUMBER;
        hash = (53 * hash) + getBuildingId();
      }
      if (hasBuildingPart()) {
        hash = (37 * hash) + BUILDING_PART_FIELD_NUMBER;
        hash = (53 * hash) + getBuildingPart().hashCode();
      }
      if (hasCellId()) {
        hash = (37 * hash) + CELL_ID_FIELD_NUMBER;
        hash = (53 * hash) + getCellId();
      }
      if (hasRoomId()) {
        hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
        hash = (53 * hash) + getRoomId();
      }
      if (hasAlarmCategory()) {
        hash = (37 * hash) + ALARM_CATEGORY_FIELD_NUMBER;
        hash = (53 * hash) + getAlarmCategory().hashCode();
      }
      if (hasAttachment()) {
        hash = (37 * hash) + ATTACHMENT_FIELD_NUMBER;
        hash = (53 * hash) + getAttachment().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Alarm parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Alarm parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Alarm parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Alarm parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Alarm parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Alarm parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Alarm parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Alarm parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Alarm parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Alarm parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Alarm parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Alarm parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Alarm prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Alarm}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Alarm)
        AlarmOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AlarmProto.internal_static_Alarm_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AlarmProto.internal_static_Alarm_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Alarm.class, Builder.class);
      }

      // Construct using com.testnetdeve.custom.proto.AlarmProto.Alarm.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        community_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        buildingId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        buildingPart_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        cellId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        roomId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        alarmCategory_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        attachment_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AlarmProto.internal_static_Alarm_descriptor;
      }

      @Override
      public Alarm getDefaultInstanceForType() {
        return Alarm.getDefaultInstance();
      }

      @Override
      public Alarm build() {
        Alarm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Alarm buildPartial() {
        Alarm result = new Alarm(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.community_ = community_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.buildingId_ = buildingId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.buildingPart_ = buildingPart_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.cellId_ = cellId_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.roomId_ = roomId_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.alarmCategory_ = alarmCategory_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.attachment_ = attachment_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Alarm) {
          return mergeFrom((Alarm)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Alarm other) {
        if (other == Alarm.getDefaultInstance()) return this;
        if (other.hasCommunity()) {
          bitField0_ |= 0x00000001;
          community_ = other.community_;
          onChanged();
        }
        if (other.hasBuildingId()) {
          setBuildingId(other.getBuildingId());
        }
        if (other.hasBuildingPart()) {
          bitField0_ |= 0x00000004;
          buildingPart_ = other.buildingPart_;
          onChanged();
        }
        if (other.hasCellId()) {
          setCellId(other.getCellId());
        }
        if (other.hasRoomId()) {
          setRoomId(other.getRoomId());
        }
        if (other.hasAlarmCategory()) {
          bitField0_ |= 0x00000020;
          alarmCategory_ = other.alarmCategory_;
          onChanged();
        }
        if (other.hasAttachment()) {
          bitField0_ |= 0x00000040;
          attachment_ = other.attachment_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasBuildingId()) {
          return false;
        }
        if (!hasCellId()) {
          return false;
        }
        if (!hasRoomId()) {
          return false;
        }
        if (!hasAlarmCategory()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Alarm parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Alarm) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object community_ = "";
      /**
       * <code>optional string community = 2;</code>
       */
      public boolean hasCommunity() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string community = 2;</code>
       */
      public String getCommunity() {
        Object ref = community_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            community_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string community = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCommunityBytes() {
        Object ref = community_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          community_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string community = 2;</code>
       */
      public Builder setCommunity(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        community_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string community = 2;</code>
       */
      public Builder clearCommunity() {
        bitField0_ = (bitField0_ & ~0x00000001);
        community_ = getDefaultInstance().getCommunity();
        onChanged();
        return this;
      }
      /**
       * <code>optional string community = 2;</code>
       */
      public Builder setCommunityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        community_ = value;
        onChanged();
        return this;
      }

      private int buildingId_ ;
      /**
       * <code>required int32 building_id = 3;</code>
       */
      public boolean hasBuildingId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 building_id = 3;</code>
       */
      public int getBuildingId() {
        return buildingId_;
      }
      /**
       * <code>required int32 building_id = 3;</code>
       */
      public Builder setBuildingId(int value) {
        bitField0_ |= 0x00000002;
        buildingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 building_id = 3;</code>
       */
      public Builder clearBuildingId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        buildingId_ = 0;
        onChanged();
        return this;
      }

      private Object buildingPart_ = "";
      /**
       * <code>optional string building_part = 4;</code>
       */
      public boolean hasBuildingPart() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string building_part = 4;</code>
       */
      public String getBuildingPart() {
        Object ref = buildingPart_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            buildingPart_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string building_part = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBuildingPartBytes() {
        Object ref = buildingPart_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          buildingPart_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string building_part = 4;</code>
       */
      public Builder setBuildingPart(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        buildingPart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string building_part = 4;</code>
       */
      public Builder clearBuildingPart() {
        bitField0_ = (bitField0_ & ~0x00000004);
        buildingPart_ = getDefaultInstance().getBuildingPart();
        onChanged();
        return this;
      }
      /**
       * <code>optional string building_part = 4;</code>
       */
      public Builder setBuildingPartBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        buildingPart_ = value;
        onChanged();
        return this;
      }

      private int cellId_ ;
      /**
       * <code>required int32 cell_id = 5;</code>
       */
      public boolean hasCellId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int32 cell_id = 5;</code>
       */
      public int getCellId() {
        return cellId_;
      }
      /**
       * <code>required int32 cell_id = 5;</code>
       */
      public Builder setCellId(int value) {
        bitField0_ |= 0x00000008;
        cellId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cell_id = 5;</code>
       */
      public Builder clearCellId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cellId_ = 0;
        onChanged();
        return this;
      }

      private int roomId_ ;
      /**
       * <code>required int32 room_id = 6;</code>
       */
      public boolean hasRoomId() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required int32 room_id = 6;</code>
       */
      public int getRoomId() {
        return roomId_;
      }
      /**
       * <code>required int32 room_id = 6;</code>
       */
      public Builder setRoomId(int value) {
        bitField0_ |= 0x00000010;
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 room_id = 6;</code>
       */
      public Builder clearRoomId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        roomId_ = 0;
        onChanged();
        return this;
      }

      private Object alarmCategory_ = "";
      /**
       * <code>required string alarm_category = 7;</code>
       */
      public boolean hasAlarmCategory() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required string alarm_category = 7;</code>
       */
      public String getAlarmCategory() {
        Object ref = alarmCategory_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            alarmCategory_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string alarm_category = 7;</code>
       */
      public com.google.protobuf.ByteString
          getAlarmCategoryBytes() {
        Object ref = alarmCategory_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          alarmCategory_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string alarm_category = 7;</code>
       */
      public Builder setAlarmCategory(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        alarmCategory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string alarm_category = 7;</code>
       */
      public Builder clearAlarmCategory() {
        bitField0_ = (bitField0_ & ~0x00000020);
        alarmCategory_ = getDefaultInstance().getAlarmCategory();
        onChanged();
        return this;
      }
      /**
       * <code>required string alarm_category = 7;</code>
       */
      public Builder setAlarmCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        alarmCategory_ = value;
        onChanged();
        return this;
      }

      private Object attachment_ = "";
      /**
       * <code>optional string attachment = 8;</code>
       */
      public boolean hasAttachment() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional string attachment = 8;</code>
       */
      public String getAttachment() {
        Object ref = attachment_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            attachment_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string attachment = 8;</code>
       */
      public com.google.protobuf.ByteString
          getAttachmentBytes() {
        Object ref = attachment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          attachment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string attachment = 8;</code>
       */
      public Builder setAttachment(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        attachment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string attachment = 8;</code>
       */
      public Builder clearAttachment() {
        bitField0_ = (bitField0_ & ~0x00000040);
        attachment_ = getDefaultInstance().getAttachment();
        onChanged();
        return this;
      }
      /**
       * <code>optional string attachment = 8;</code>
       */
      public Builder setAttachmentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        attachment_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Alarm)
    }

    // @@protoc_insertion_point(class_scope:Alarm)
    private static final Alarm DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Alarm();
    }

    public static Alarm getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Alarm>
        PARSER = new com.google.protobuf.AbstractParser<Alarm>() {
      @Override
      public Alarm parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Alarm(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Alarm> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Alarm> getParserForType() {
      return PARSER;
    }

    @Override
    public Alarm getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Alarm_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Alarm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013alarm.proto\"\224\001\n\005Alarm\022\021\n\tcommunity\030\002 \001" +
      "(\t\022\023\n\013building_id\030\003 \002(\005\022\025\n\rbuilding_part" +
      "\030\004 \001(\t\022\017\n\007cell_id\030\005 \002(\005\022\017\n\007room_id\030\006 \002(\005" +
      "\022\026\n\016alarm_category\030\007 \002(\t\022\022\n\nattachment\030\010" +
      " \001(\tB*\n\034com.testnetdeve.custom.protoB\nAl" +
      "armProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Alarm_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Alarm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Alarm_descriptor,
        new String[] { "Community", "BuildingId", "BuildingPart", "CellId", "RoomId", "AlarmCategory", "Attachment", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
